
CREATE TABLE clientes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    cpf_cnpj VARCHAR(20),
    telefone VARCHAR(20) NOT NULL,
    email VARCHAR(150),
    cep VARCHAR(10),
    rua VARCHAR(150),
    numero VARCHAR(20),
    bairro VARCHAR(100),
    cidade VARCHAR(100),
    estado CHAR(2),
    ativo SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_clientes_cpf_cnpj UNIQUE (cpf_cnpj),
    CONSTRAINT chk_clientes_ativo CHECK (ativo IN (0,1)),
    CONSTRAINT chk_clientes_estado CHECK (estado IS NULL OR UPPER(estado) IN ('AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO'))
);

CREATE TABLE funcionarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    telefone VARCHAR(20),
    email VARCHAR(150),
    cargo VARCHAR(50) NOT NULL,
    data_admissao DATE,
    salario NUMERIC(10,2),
    percentual_comissao NUMERIC(5,2),
    ativo SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tipo_vinculo VARCHAR(20) NOT NULL DEFAULT 'FIXO',
    valor_diaria NUMERIC(10,2),
    CONSTRAINT chk_funcionarios_salario CHECK (salario IS NULL OR salario >= 0),
    CONSTRAINT chk_funcionarios_comissao CHECK (percentual_comissao IS NULL OR percentual_comissao BETWEEN 0 AND 100),
    CONSTRAINT chk_funcionarios_valor_diaria CHECK (valor_diaria IS NULL OR valor_diaria >= 0),
    CONSTRAINT chk_funcionarios_tipo_vinculo CHECK (tipo_vinculo IN ('FIXO','FREELANCE')),
    CONSTRAINT chk_funcionarios_vinculo_valores CHECK ((tipo_vinculo = 'FIXO' AND valor_diaria IS NULL) OR (tipo_vinculo = 'FREELANCE' AND salario IS NULL)),
    CONSTRAINT chk_funcionarios_ativo CHECK (ativo IN (0,1))
);

CREATE TABLE fornecedores (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    cpf_cnpj VARCHAR(20),
    telefone VARCHAR(20),
    email VARCHAR(150),
    cep VARCHAR(10),
    rua VARCHAR(150),
    numero VARCHAR(20),
    bairro VARCHAR(100),
    cidade VARCHAR(100),
    estado CHAR(2),
    ativo SMALLINT NOT NULL DEFAULT 1,
    observacao VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_fornecedores_cpf_cnpj UNIQUE (cpf_cnpj),
    CONSTRAINT chk_fornecedores_ativo CHECK (ativo IN (0,1)),
    CONSTRAINT chk_fornecedores_estado CHECK (estado IS NULL OR UPPER(estado) IN ('AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE','PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO'))
);

CREATE TABLE pecas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    descricao VARCHAR(255),
    marca VARCHAR(80),
    valor_custo NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    valor_venda NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    estoque INTEGER NOT NULL DEFAULT 0,
    estoque_minimo INTEGER NOT NULL DEFAULT 0,
    ativo SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_pecas_estoque CHECK (estoque >= 0),
    CONSTRAINT chk_pecas_valor_custo CHECK (valor_custo >= 0),
    CONSTRAINT chk_pecas_valor_venda CHECK (valor_venda >= 0),
    CONSTRAINT chk_pecas_estoque_minimo CHECK (estoque_minimo >= 0),
    CONSTRAINT chk_pecas_ativo CHECK (ativo IN (0,1))
);

CREATE TABLE servicos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao VARCHAR(255),
    valor_padrao NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    ativo SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_servicos_nome UNIQUE (nome),
    CONSTRAINT chk_servicos_valor_padrao CHECK (valor_padrao >= 0),
    CONSTRAINT chk_servicos_ativo CHECK (ativo IN (0,1))
);

CREATE TABLE veiculos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id INTEGER NOT NULL,
    placa VARCHAR(8) NOT NULL,
    marca VARCHAR(50) NOT NULL,
    modelo VARCHAR(80),
    ano SMALLINT,
    ativo SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_veiculo_placa UNIQUE (placa),
    CONSTRAINT fk_veiculos_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON UPDATE CASCADE,
    CONSTRAINT chk_veiculos_ano CHECK (ano IS NULL OR ano BETWEEN 1900 AND 2100),
    CONSTRAINT chk_veiculos_ativo CHECK (ativo IN (0,1))
);
CREATE INDEX idx_veiculos_cliente ON veiculos(cliente_id);

CREATE TABLE usuarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(80) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    perfil VARCHAR(30) NOT NULL,
    ativo SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    funcionario_id INTEGER NOT NULL,
    CONSTRAINT uk_usuarios_login UNIQUE (login),
    CONSTRAINT uk_usuarios_funcionario UNIQUE (funcionario_id),
    CONSTRAINT fk_usuarios_funcionario FOREIGN KEY (funcionario_id) REFERENCES funcionarios(id),
    CONSTRAINT chk_usuarios_perfil CHECK (perfil IN ('ADMIN','ATENDENTE','MECANICO')),
    CONSTRAINT chk_usuarios_ativo CHECK (ativo IN (0,1))
);

CREATE TABLE diarias_funcionarios (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    funcionario_id INTEGER NOT NULL,
    data_trabalho DATE NOT NULL,
    valor_diaria NUMERIC(10,2) NOT NULL,
    observacao VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_funcionario_data UNIQUE (funcionario_id, data_trabalho),
    CONSTRAINT fk_diarias_funcionario FOREIGN KEY (funcionario_id) REFERENCES funcionarios(id),
    CONSTRAINT chk_diarias_valor CHECK (valor_diaria >= 0)
);

CREATE TABLE compras (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fornecedor_id INTEGER NOT NULL,
    numero_documento VARCHAR(50),
    data_compra DATE NOT NULL,
    valor_total NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    status_recebimento VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    observacao VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_compras_fornecedor FOREIGN KEY (fornecedor_id) REFERENCES fornecedores(id),
    CONSTRAINT chk_compras_valor_total CHECK (valor_total >= 0),
    CONSTRAINT chk_compras_status_recebimento CHECK (status_recebimento IN ('PENDENTE','RECEBIDO','CANCELADO'))
);
CREATE INDEX idx_compras_fornecedor ON compras(fornecedor_id);

CREATE TABLE despesas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(150) NOT NULL,
    categoria VARCHAR(50) NOT NULL,
    valor NUMERIC(10,2) NOT NULL,
    data_despesa DATE NOT NULL,
    fornecedor_id INTEGER,
    observacao VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_despesas_fornecedor FOREIGN KEY (fornecedor_id) REFERENCES fornecedores(id),
    CONSTRAINT chk_despesas_valor CHECK (valor >= 0)
);
CREATE INDEX idx_despesas_fornecedor ON despesas(fornecedor_id);

CREATE TABLE ordens_servico (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    veiculo_id INTEGER NOT NULL,
    data_abertura TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_fechamento TIMESTAMP,
    status VARCHAR(30) NOT NULL DEFAULT 'ABERTA',
    problema_relatado TEXT,
    observacoes TEXT,
    valor_servicos NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    valor_pecas NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ordens_servico_veiculo FOREIGN KEY (veiculo_id) REFERENCES veiculos(id),
    CONSTRAINT chk_ordens_valor_servicos CHECK (valor_servicos >= 0),
    CONSTRAINT chk_ordens_valor_pecas CHECK (valor_pecas >= 0),
    CONSTRAINT chk_ordens_status CHECK (status IN ('ABERTA','EM_ANDAMENTO','FINALIZADA','CANCELADA')),
    CONSTRAINT chk_ordens_datas CHECK (data_fechamento IS NULL OR data_fechamento >= data_abertura),
    CONSTRAINT chk_ordens_status_fechamento CHECK (((status IN ('ABERTA','EM_ANDAMENTO')) AND data_fechamento IS NULL) OR ((status IN ('FINALIZADA','CANCELADA')) AND data_fechamento IS NOT NULL))
);
CREATE INDEX idx_ordens_servico_veiculo ON ordens_servico(veiculo_id);

CREATE TABLE ordem_servico_pecas (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ordem_servico_id INTEGER NOT NULL,
    peca_id INTEGER NOT NULL,
    quantidade INTEGER NOT NULL DEFAULT 1,
    valor_unitario NUMERIC(10,2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_os_pecas_ordem FOREIGN KEY (ordem_servico_id) REFERENCES ordens_servico(id),
    CONSTRAINT fk_os_pecas_peca FOREIGN KEY (peca_id) REFERENCES pecas(id),
    CONSTRAINT chk_os_pecas_quantidade CHECK (quantidade > 0),
    CONSTRAINT chk_os_pecas_valor_unitario CHECK (valor_unitario >= 0)
);
CREATE INDEX idx_os_pecas_ordem ON ordem_servico_pecas(ordem_servico_id);
CREATE INDEX idx_os_pecas_peca ON ordem_servico_pecas(peca_id);

CREATE TABLE ordem_servico_servicos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ordem_servico_id INTEGER NOT NULL,
    servico_id INTEGER NOT NULL,
    quantidade INTEGER NOT NULL DEFAULT 1,
    valor_unitario NUMERIC(10,2) NOT NULL,
    observacao VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    funcionario_id INTEGER,
    CONSTRAINT fk_os_servicos_funcionario FOREIGN KEY (funcionario_id) REFERENCES funcionarios(id),
    CONSTRAINT fk_os_servicos_ordem FOREIGN KEY (ordem_servico_id) REFERENCES ordens_servico(id),
    CONSTRAINT fk_os_servicos_servico FOREIGN KEY (servico_id) REFERENCES servicos(id),
    CONSTRAINT chk_os_servicos_quantidade CHECK (quantidade > 0),
    CONSTRAINT chk_os_servicos_valor_unitario CHECK (valor_unitario >= 0)
);
CREATE INDEX idx_os_servicos_ordem ON ordem_servico_servicos(ordem_servico_id);
CREATE INDEX idx_os_servicos_servico ON ordem_servico_servicos(servico_id);
CREATE INDEX idx_os_servicos_funcionario ON ordem_servico_servicos(funcionario_id);

CREATE TABLE itens_compra (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id INTEGER NOT NULL,
    peca_id INTEGER NOT NULL,
    quantidade INTEGER NOT NULL,
    valor_unitario NUMERIC(10,2) NOT NULL,
    subtotal NUMERIC(10,2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_itens_compra_compra FOREIGN KEY (compra_id) REFERENCES compras(id),
    CONSTRAINT fk_itens_compra_peca FOREIGN KEY (peca_id) REFERENCES pecas(id),
    CONSTRAINT chk_itens_compra_quantidade CHECK (quantidade > 0),
    CONSTRAINT chk_itens_compra_valor_unitario CHECK (valor_unitario >= 0),
    CONSTRAINT chk_itens_compra_subtotal CHECK (subtotal >= 0)
);
CREATE INDEX idx_itens_compra_compra ON itens_compra(compra_id);
CREATE INDEX idx_itens_compra_peca ON itens_compra(peca_id);

CREATE TABLE movimentacoes_estoque (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    peca_id INTEGER NOT NULL,
    tipo VARCHAR(20) NOT NULL,
    quantidade INTEGER NOT NULL,
    valor_unitario NUMERIC(10,2),
    ordem_servico_id INTEGER,
    ordem_servico_peca_id INTEGER,
    fornecedor_id INTEGER,
    compra_id INTEGER,
    observacao VARCHAR(255),
    data_movimentacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    os_peca_saida_unica INTEGER GENERATED ALWAYS AS (CASE WHEN tipo = 'SAIDA' THEN ordem_servico_peca_id ELSE NULL END) STORED,
    CONSTRAINT uk_mov_estoque_compra_peca_tipo UNIQUE (compra_id, peca_id, tipo),
    CONSTRAINT uk_mov_estoque_os_peca_saida UNIQUE (os_peca_saida_unica),
    CONSTRAINT fk_movimentacao_compra FOREIGN KEY (compra_id) REFERENCES compras(id),
    CONSTRAINT fk_movimentacao_fornecedor FOREIGN KEY (fornecedor_id) REFERENCES fornecedores(id),
    CONSTRAINT fk_movimentacao_ordem FOREIGN KEY (ordem_servico_id) REFERENCES ordens_servico(id),
    CONSTRAINT fk_movimentacao_os_peca FOREIGN KEY (ordem_servico_peca_id) REFERENCES ordem_servico_pecas(id),
    CONSTRAINT fk_movimentacao_peca FOREIGN KEY (peca_id) REFERENCES pecas(id),
    CONSTRAINT chk_movimentacoes_quantidade CHECK (quantidade > 0),
    CONSTRAINT chk_movimentacoes_valor_unitario CHECK (valor_unitario IS NULL OR valor_unitario >= 0),
    CONSTRAINT chk_movimentacoes_tipo CHECK (tipo IN ('ENTRADA','SAIDA','AJUSTE_ENTRADA','AJUSTE_SAIDA'))
);
CREATE INDEX idx_movimentacao_peca ON movimentacoes_estoque(peca_id);
CREATE INDEX idx_movimentacao_ordem ON movimentacoes_estoque(ordem_servico_id);
CREATE INDEX idx_movimentacao_fornecedor ON movimentacoes_estoque(fornecedor_id);
CREATE INDEX idx_movimentacao_os_peca ON movimentacoes_estoque(ordem_servico_peca_id);

CREATE TABLE contas_pagar (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id INTEGER,
    despesa_id INTEGER,
    diaria_funcionario_id INTEGER,
    fornecedor_id INTEGER,
    descricao VARCHAR(150) NOT NULL,
    valor_total NUMERIC(10,2) NOT NULL,
    data_emissao DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    observacao VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_contas_pagar_diaria UNIQUE (diaria_funcionario_id),
    CONSTRAINT uk_contas_pagar_compra UNIQUE (compra_id),
    CONSTRAINT uk_contas_pagar_despesa UNIQUE (despesa_id),
    CONSTRAINT fk_contas_pagar_compra FOREIGN KEY (compra_id) REFERENCES compras(id),
    CONSTRAINT fk_contas_pagar_despesa FOREIGN KEY (despesa_id) REFERENCES despesas(id),
    CONSTRAINT fk_contas_pagar_diaria FOREIGN KEY (diaria_funcionario_id) REFERENCES diarias_funcionarios(id),
    CONSTRAINT fk_contas_pagar_fornecedor FOREIGN KEY (fornecedor_id) REFERENCES fornecedores(id),
    CONSTRAINT chk_contas_pagar_valor_total CHECK (valor_total >= 0),
    CONSTRAINT chk_contas_pagar_status CHECK (status IN ('PENDENTE','PARCIAL','PAGO','CANCELADO')),
    CONSTRAINT chk_contas_pagar_origem CHECK ((CASE WHEN compra_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN despesa_id IS NOT NULL THEN 1 ELSE 0 END) + (CASE WHEN diaria_funcionario_id IS NOT NULL THEN 1 ELSE 0 END) <= 1)
);
CREATE INDEX idx_contas_pagar_fornecedor ON contas_pagar(fornecedor_id);

CREATE TABLE parcelas_contas_pagar (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_pagar_id INTEGER NOT NULL,
    numero_parcela INTEGER NOT NULL,
    valor_parcela NUMERIC(10,2) NOT NULL,
    data_vencimento DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    observacao VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_conta_numero_parcela UNIQUE (conta_pagar_id, numero_parcela),
    CONSTRAINT fk_parcelas_conta_pagar FOREIGN KEY (conta_pagar_id) REFERENCES contas_pagar(id),
    CONSTRAINT chk_parcelas_pagar_valor CHECK (valor_parcela >= 0),
    CONSTRAINT chk_parcelas_pagar_status CHECK (status IN ('PENDENTE','PARCIAL','PAGO','CANCELADO')),
    CONSTRAINT chk_parcelas_pagar_numero CHECK (numero_parcela > 0)
);
CREATE INDEX idx_parcelas_pagar_status_vencimento ON parcelas_contas_pagar(status, data_vencimento);

CREATE TABLE pagamentos_contas_pagar (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parcela_id INTEGER NOT NULL,
    valor_pago NUMERIC(10,2) NOT NULL,
    data_pagamento TIMESTAMP NOT NULL,
    forma_pagamento VARCHAR(30),
    observacao VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pagamentos_parcela FOREIGN KEY (parcela_id) REFERENCES parcelas_contas_pagar(id),
    CONSTRAINT chk_pagamentos_pagar_valor CHECK (valor_pago > 0)
);
CREATE INDEX idx_pagamentos_pagar_parcela ON pagamentos_contas_pagar(parcela_id);

CREATE TABLE contas_receber (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ordem_servico_id INTEGER NOT NULL,
    descricao VARCHAR(150) NOT NULL,
    valor_total NUMERIC(10,2) NOT NULL,
    data_emissao DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    observacao VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_contas_receber_ordem_servico UNIQUE (ordem_servico_id),
    CONSTRAINT fk_contas_receber_ordem_servico FOREIGN KEY (ordem_servico_id) REFERENCES ordens_servico(id),
    CONSTRAINT chk_contas_receber_valor_total CHECK (valor_total >= 0),
    CONSTRAINT chk_contas_receber_status CHECK (status IN ('PENDENTE','PARCIAL','PAGO','CANCELADO'))
);

CREATE TABLE parcelas_contas_receber (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conta_receber_id INTEGER NOT NULL,
    numero_parcela INTEGER NOT NULL,
    valor_parcela NUMERIC(10,2) NOT NULL,
    data_vencimento DATE NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    observacao VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_conta_receber_numero_parcela UNIQUE (conta_receber_id, numero_parcela),
    CONSTRAINT fk_parcelas_conta_receber FOREIGN KEY (conta_receber_id) REFERENCES contas_receber(id),
    CONSTRAINT chk_parcelas_receber_valor CHECK (valor_parcela >= 0),
    CONSTRAINT chk_parcelas_receber_status CHECK (status IN ('PENDENTE','PARCIAL','PAGO','CANCELADO')),
    CONSTRAINT chk_parcelas_receber_numero CHECK (numero_parcela > 0)
);
CREATE INDEX idx_parcelas_receber_status_vencimento ON parcelas_contas_receber(status, data_vencimento);

CREATE TABLE pagamentos_contas_receber (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parcela_id INTEGER NOT NULL,
    valor_pago NUMERIC(10,2) NOT NULL,
    data_pagamento TIMESTAMP NOT NULL,
    forma_pagamento VARCHAR(30),
    observacao VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pagamentos_conta_receber_parcela FOREIGN KEY (parcela_id) REFERENCES parcelas_contas_receber(id),
    CONSTRAINT chk_pagamentos_receber_valor CHECK (valor_pago > 0)
);
CREATE INDEX idx_pagamentos_receber_parcela ON pagamentos_contas_receber(parcela_id);


